# Generated by Django 5.1.7 on 2025-07-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=100)),
                ('mission', models.TextField()),
                ('logo', models.ImageField(upload_to='associations/')),
                ('contact', models.EmailField(max_length=254)),
            ],
        ),
    ]
