# Generated by Django 5.1.7 on 2025-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='mission',
            new_name='resume',
        ),
        migrations.RemoveField(
            model_name='association',
            name='contact',
        ),
        migrations.AddField(
            model_name='association',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.ImageField(upload_to='images/associations/'),
        ),
    ]
