# Generated by Django 5.1.7 on 2025-07-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('biographie', models.TextField()),
                ('photo', models.ImageField(upload_to='personnalites/')),
            ],
        ),
    ]
