# Generated by Django 5.1.7 on 2025-07-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnalites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnalite',
            name='slug',
            field=models.SlugField(default='inconnu', unique=True),
        ),
        migrations.AlterField(
            model_name='personnalite',
            name='fonction',
            field=models.CharField(max_length=150),
        ),
    ]
