# Generated by Django 5.1.7 on 2025-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen', models.CharField(choices=[('momo', 'Mobile Money'), ('carte', 'Carte bancaire')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
