# Generated by Django 5.1.7 on 2025-07-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='moyen',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('carte', 'Carte bancaire'), ('OM', 'Orange Money')], max_length=10),
        ),
    ]
