# Generated by Django 5.1.7 on 2025-07-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0002_alter_don_moyen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='don',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='don',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='don',
            name='moyen',
            field=models.CharField(choices=[('OM', 'Orange Money'), ('MOMO', 'Mobile Money')], max_length=10),
        ),
        migrations.AddField(
            model_name='don',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dons', to='dons.projet'),
        ),
    ]
