# Generated by Django 5.1.7 on 2025-07-06 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0003_projet_don_message_don_numero_alter_don_moyen_and_more'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='projet',
            field=models.ForeignKey(default='0000000000', on_delete=django.db.models.deletion.CASCADE, to='projets.projet'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='don',
            name='message',
        ),
        migrations.AlterField(
            model_name='don',
            name='moyen',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('OM', 'Orange Money')], max_length=10),
        ),
        migrations.AlterField(
            model_name='don',
            name='numero',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
    ]
