# Generated by Django 5.1.7 on 2025-07-07 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0004_alter_don_projet_remove_don_message_alter_don_moyen_and_more'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='don',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projets.projet'),
        ),
    ]
