# Generated by Django 5.1.7 on 2025-07-07 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0005_alter_don_numero_alter_don_projet'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='don',
            name='projet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='projets.projet'),
            preserve_default=False,
        ),
    ]
