# Generated by Django 5.1.7 on 2025-07-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0006_don_created_at_alter_don_projet'),
        ('projets', '0002_rename_titre_projet_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.projet'),
        ),
    ]
