# Generated by Django 5.1.7 on 2025-07-08 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0007_alter_don_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='don',
            name='moyen',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('om', 'Orange Money')], max_length=10),
        ),
    ]
