# Generated by Django 5.1.7 on 2025-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0008_alter_don_created_at_alter_don_moyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
