# Generated by Django 5.1.7 on 2025-07-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dons', '0009_alter_don_created_at'),
        ('projets', '0004_alter_projet_date_lancement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don',
            name='date',
        ),
        migrations.AlterField(
            model_name='don',
            name='montant',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='don',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='projets.projet'),
        ),
    ]
