# Generated by Django 5.1.7 on 2025-07-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projets/')),
                ('etat', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('a_venir', 'À venir')], default='en_cours', max_length=20)),
                ('partenaires', models.TextField(help_text='Séparer les noms par des virgules')),
            ],
        ),
    ]
