# Generated by Django 5.1.7 on 2025-07-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='titre',
            new_name='nom',
        ),
    ]
