# Generated by Django 5.1.7 on 2025-07-14 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_rename_titre_projet_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='nom',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='partenaires',
        ),
        migrations.AddField(
            model_name='projet',
            name='date_lancement',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
