# Generated by Django 5.1.7 on 2025-07-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_rename_nom_projet_titre_remove_projet_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_lancement',
            field=models.DateField(),
        ),
    ]
