# Generated by Django 5.1.7 on 2025-07-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_alter_projet_date_lancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projets/images/'),
        ),
    ]
