# Generated by Django 5.1.7 on 2025-07-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
