# Generated by Django 5.1.7 on 2025-07-05 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_actualite_image_actualite_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualite',
            name='date_publication',
        ),
        migrations.AddField(
            model_name='actualite',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='actualites/'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
